services:
  - type: web
    name: openflip
    runtime: docker
    dockerfilePath: ./Dockerfile
    port: 8000
    healthCheckPath: /
    envVars:
      - key: MAX_FILE_SIZE
        value: 52428800
      - key: PYTHONUNBUFFERED
        value: "1"
    autoDeploy: true
    disk:
      name: storage
      mountPath: /app/storage
      sizeGB: 10
